services:
  - type: web
    name: plataforma-creditos
    env: static
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/PlataformaCreditos.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: ConnectionStrings__DefaultConnection
        value: DataSource=app.db
      - key: Redis__ConnectionString
        value: redis-17073.c270.us-east-1-3.ec2.cloud.redislabs.com:17073,password=mL4jU6KqI5JAEGBwIdciCLAP49oNHOWj,ssl=false,abortConnect=false